version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.0

lambda:

description: >
  Build and release steps for AWS Step Functions.

executors:
  default:
    docker:
      - image: cimg/python:3.9.2

commands:
  validate:
    parameters:
      file:
        default: step-function.json
        type: string
      path:
        default: .
        type: string
    steps:
      - run:
          name: Validate Step Function JSON
          working_directory: << parameters.path >>
          command: |
            python -c "import json; import sys; json.load(sys.stdin)" < ./<< parameters.file >>
  update-step-function-cache:
    parameters:
      file:
        default: step-function.json
        type: string
      path:
        default: .
        type: string
    steps:
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
  restore-step-function-cache:
    parameters:
      file:
        default: step-function.json
        type: string
      path:
        default: .
        type: string
    steps:
      - attach_workspace:
          at: /home/circleci

  deploy:
    parameters:
      account_id:
        type: string
      environment:
        type: string
      executor:
        type: executor
        default: default
      file:
        default: step-function.json
        type: string
      path:
        default: .
        type: string
      region:
        type: string
      step_function:
        type: string
    steps:
      - run:
          name: Update << parameters.step_function >> Step Function
          working_directory: << parameters.path >>
          environment:
            AWS_PAGER: ""
          command: |
            pwd
            ls
            aws --region << parameters.region >> \
              stepfunctions update-state-machine \
              --state-machine-arn arn:aws:states:<< parameters.region >>:<< parameters.account_id >>:stateMachine:<< parameters.environment >>-<< parameters.step_function >> \
              --definition "$(sed -e 's/ENVIRONMENT/<< parameters.environment >>/g' -e 's/REGION/<< parameters.region >>/g' ./<< parameters.file>>)"

jobs:
  build:
    parameters:
      executor:
        type: executor
        default: default
      file:
        default: step-function.json
        type: string
      path:
        default: .
        type: string

    executor: << parameters.executor >>

    steps:
      - checkout
      - validate:
          file: << parameters.file >>
          path: << parameters.path >>
      - update-step-function-cache:
          file: << parameters.file >>
          path: << parameters.path >>

  deploy:
    parameters:
      account_id:
        type: string
      environment:
        type: string
      executor:
        type: executor
        default: default
      file:
        default: step-function.json
        type: string
      path:
        default: .
        type: string
      region:
        type: string
      step_function:
        type: string

    executor: << parameters.executor >>

    steps:
      - restore-step-function-cache:
          file: << parameters.file >>
          path: << parameters.path >>
      - aws-cli/install
      - deploy:
          account_id: << parameters.account_id >>
          environment: << parameters.environment >>
          file: << parameters.file >>
          path: << parameters.path >>
          region: << parameters.region >>
          step_function: << parameters.step_function >>
