version: 2.1

description: >
  Build and release steps for Python projects.

executors:
  default:
    docker:
      - image: cimg/python:3.9.2

commands:
  install-dependencies:
    parameters:
      path:
        default: .
        type: string
    steps:
      - run:
          name: Install Dependencies
          working_directory: << parameters.path >>
          command: |
            pip install .[lint,test,typehinting]
  lint:
    parameters:
      path:
        default: .
        type: string
      source:
        default: .
        type: string
    steps:
      - run:
          name: Run flake8
          working_directory: << parameters.path >>
          command: |
            flake8 << parameters.source >>
  test:
    parameters:
      path:
        default: .
        type: string
      source:
        default: .
        type: string
    steps:
      - run:
          name: Run nosetests
          working_directory: << parameters.path >>
          command: |
            nosetests << parameters.source >>

  typehinting:
    parameters:
      path:
        default: .
        type: string
      source:
        default: .
        type: string
    steps:
      - run:
          name: Run mypy
          working_directory: << parameters.path >>
          command: |
            mypy << parameters.source >>

  restore-dependencies-cache:
    steps:
      - attach_workspace:
          at: /home/circleci

  update-dependencies-cache:
    steps:
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .pyenv
            - project

jobs:
  build:
    parameters:
      executor:
        type: executor
        default: default
      path:
        default: .
        type: string
      source:
        default: .
        type: string

    executor: << parameters.executor >>

    steps:
      - checkout
      - install-dependencies:
          path: << parameters.path >>
      - lint:
          path: << parameters.path >>
          source: << parameters.source >>
      - typehinting:
          path: << parameters.path >>
          source: << parameters.source >>
      - test:
          path: << parameters.path >>
          source: << parameters.source >>
      - update-dependencies-cache
