version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.0

description: >
  Build and release steps for AWS Lambda functions.

executors:
  default:
    docker:
      - image: cimg/python:3.9.2

commands:
  build-lambda:
    parameters:
      lambda:
        type: string
      path:
        default: .
        type: string
    steps:
      - run:
          name: Build << parameters.lambda >> Deployment Package
          working_directory: << parameters.path >>
          command: |
            zip << parameters.lambda >>.zip $(find . -name "*.py" ! -name "setup.py" ! -path "*/tests/*" ! -path "*/cli/*")

  deploy-lambda:
    parameters:
      bucket:
        type: string
      environment:
        type: string
      handler:
        type: string
      lambda:
        type: string
      path:
        default: .
        type: string
    steps:
      - run:
          name: Upload << parameters.lambda >> Deployment Package
          working_directory: << parameters.path >>
          command: |
            aws s3 cp << parameters.lambda >>.zip s3://<< parameters.bucket >>/functions/<< parameters.environment >>/<< parameters.lambda >>.zip
      - run:
          name: Upload << parameters.lambda >> Function Code
          environment:
            AWS_PAGER: ""
          command: |
            aws lambda update-function-code \
              --function-name << parameters.environment >>-<< parameters.lambda >> \
              --s3-bucket << parameters.bucket >> \
              --s3-key functions/<< parameters.environment >>/<< parameters.lambda >>.zip
      - run:
          name: Upload << parameters.lambda >> Function Configuration
          environment:
            AWS_PAGER: ""
          command: |
            aws lambda update-function-configuration \
              --function-name << parameters.environment >>-<< parameters.lambda >> \
              --handler << parameters.handler >>
